# Generated by Django 3.1.7 on 2021-02-28 21:57

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('app', '0002_profile_status'),
	]

	operations = [
		migrations.RemoveField(
			model_name='profile',
			name='image',
		),
	]
