# Generated by Django 3.1.7 on 2021-02-28 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status'),
        ),
    ]
