# Generated by Django 3.1.7 on 2021-03-03 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('app', '0004_auto_20210228_2201'),
	]

	operations = [
		migrations.AlterField(
			model_name='profile',
			name='User',
			field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile',
									   to=settings.AUTH_USER_MODEL),
		),
	]
