# Generated by Django 3.1.7 on 2021-03-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210308_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.calendarentry'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.calendarentry'),
        ),
    ]
