# Generated by Django 3.1.7 on 2021-03-11 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20210311_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='inhabitants',
            field=models.ManyToManyField(through='app.HouseMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
