# Generated by Django 3.1.7 on 2021-03-12 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_house_inhabitants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rent', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='app.house')),
                ('inhabitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhabitant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
