# Generated by Django 3.1.7 on 2021-03-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='app.house'),
        ),
    ]
