# Generated by Django 3.1.6 on 2021-03-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210315_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
