# Generated by Django 3.1.7 on 2021-03-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210316_1331'),
        ('app', '0015_auto_20210315_1546'),
    ]

    operations = [
    ]
