# Generated by Django 3.1.7 on 2021-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20210316_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
